### PR TITLE
Fix SplitView

### PR DESCRIPTION
**Pull request by Evangelink**
As far as I can tell the SplitView now correctly mimics the Windows 10 control.

### CODE REVIEW

**Comment by Evangelink** [comment]
I think it is easier to read when animations are in the XAML file but we could also set all animations within the .cs file. Don't know what is the best.

**Comment by Evangelink** [comment]
@dotMorten ping! Could you have a look to the different PR so we could have a clear idea of what else has to be fixed. I am really interested in using this library.

Thanks

**Comment by dotMorten** [comment]
Sorry for not following up on this. I couldn't originally accept this PR as there was a slew of unrelated changes unrelated to the fix. At this point it's too outdated though.

**Comment by Evangelink** [comment]
@dotMorten Hi! No worries! I don't know what's your plan for this repo but I might be able to create a new PR if that's something you find useful.

**Comment by dotMorten** [comment]
Sure that would be great, but please keep the PR small and targeted at the fix, and not do major refactoring. It makes it impossible for me to review or understand.

**Comment by dotMorten** [comment]
... I do plan of rewriting this once WinUI publishes the full splitview source which hopefully would be very soon

**Comment by Evangelink** [comment]
Makes sense! WinUI is moving pretty fast so it's probably better to wait for the refactoring.

**Comment by dotMorten** [comment]
Yeah. Took almost no time to port TwoPaneView and then guaranteed the behavior is identical.

**Pull request closed without merging**
